[package]
name = "chromatic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
winit = "0.28.3"
pixels = "0.12.0"
env_logger = "0.10.0"